### ISSUE TITLE
Upgrade to null-safety

### ISSUE THREAD

**Issue by kallaspriit** [floitsch/ranking#2]
Please support null-safety :)

**Comment by ciriousjoker** [comment]
@floitsch Can you upgrade this package to null safety, this would be the last missing dependency?
If not, do you accept pull requests?

**Comment by floitsch** [comment]
Sorry. missed the issue.
The package should be null-aware now.

**Comment by ciriousjoker** [comment]
Well, that was fast :D Thanks!
